version: 1
listing-sites:
  - url: https://cari.scholarship.or.id/listings/
    type: pagination
    listings:
      selector: "article.hp-listing"
      item:
        link: "h4.hp-listing__title>a"
  - url: https://bigfuture.collegeboard.org/scholarships
    type: single
    listings:
      selector: "div.td-cpt-post"
      item:
        link: "div.td-read-more>a"
  - url: https://www.scholarshipregion.com/category/scholarships/undergraduate-scholarships/

  - url: https://www.ziprecruiter.ie/jobs/search?q=&l=&lat=&long=&d=
    type: pagination
    listings:
      selector: "li.job-listing"
      item:
        link: "a.job-link"
  - url: https://cord.com/search/jobs
    type: scroll
    listings:
      selector: "a.position_card"
      item:
        link: "a.position_card"
  - url: https://id.jobstreet.com/id/jobs
    type: pagination
    listings:
      selector: "article"
      item:
        link: 'a[data-automation="job-list-item-link-overlay"]'
  - url: https://www.dice.com/jobs
    type: pagination
    listings:
      selector: 'div[role="listitem"]'
      item:
        link: 'a[data-testid="job-search-job-card-link"]'
  - url: https://diversityjobs.com/candidate/job_search/quick/results?keyword=&location=&op=Find+Jobs&gacid=&form_id=jj_frontpage_searchform&gacid_enabled=true&gacid_termlist=
    type: pagination
    listings:
      selector: 'div[id="s-res"]'
      item:
        link: 'p.job-title>a'
single-sites:
  - url: https://www.scholarshipdiary.com/list-of-available-scholarships-in-2025/
  - url: https://scholarshiproar.com/fully-funded-scholarships/
  - url: https://globalscholarships.com/fully-funded-scholarships/
  - url: https://opportunitiescorners.com/top-10-scholarships/
  - url: https://www.scholars4dev.com/6499/scholarships-in-usa-for-international-students/
